version = 0.1

[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sales-transcriber"
s3_prefix = "sales-transcriber"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM"
disable_rollback = false
